services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: imtihon_final_app
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - imtihon_final
    db:
        image: postgres:15
        container_name: imtihon_final_db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5435:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - imtihon_final
    nginx:
        image: nginx:alpine
        container_name: imtihon_final_nginx
        ports:
            - "88:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - imtihon_final
    redis:
        image: redis:alpine
        container_name: imtihon_final_redis
        ports:
            - "6379:6379"
        networks:
            - imtihon_final
volumes:
    pgdata:

networks:
    imtihon_final:
